---
title: "Develop_Kmean_CovM_Correlation_in_outV2"
output: html_document
date: "2023-12-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

freshr::freshr()
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set (theme_classic(base_size = 10, base_family = "sans"))

##libraries for color
library(ggsci)
library(wesanderson)
#names(wes_palettes)
library(colorBlindness)
library(viridis)

library(here)
# only work this way, when code is located in analysis folder
source (here("src", "Develop_Function_posthoc_20230219.R"))
load (here("output","2023-12-04_SummaryDevAll_Kmean_CovM_Corr_in_outV2_20231204.RData"))
```



# r_allpair_mean
```{r,fig.width = 4, fig.asp = 0.5, echo = FALSE}
#Facet by layer
plot_raw_boot_facet_layer ("r_allpair_mean",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(0, 1), 
                            #legend_position = c(0.4, 0.85)
                            legend_position = "none")

#ggsave("r_allpair_mean-facetLayer.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")

#Facet by sex
plot_raw_boot_facet_sex ("r_allpair_mean",
                          y_breaks = c(1:6 * 0.2), 
                          y_limits = c(0, 1), 
                          #legend_position = c(0.3, 0.8),
                          legend_position = "none")

#ggsave("r_allpair_mean-facetSex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")
```

```{r, fig.width = 5, fig.asp = 0.5}
report_main_effect("r_allpair_mean")
#full comparison
report_inter_age_sex_layer("r_allpair_mean")
```


# in_r_mean
```{r,fig.width = 4, fig.asp = 0.5, echo = FALSE}
#Facet by layer
plot_raw_boot_facet_layer ("in_r_mean",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(0, 1), 
                            #legend_position = c(0.4, 0.8)
                            legend_position = "none")

#ggsave("cluster_r_all_mean_facet_layer.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")

#Facet by sex
plot_raw_boot_facet_sex ("in_r_mean",
                          y_breaks = c(1:6 * 0.2), 
                          y_limits = c(0, 1), 
                          #legend_position = c(0.2, 0.8),
                          legend_position = "none")

#ggsave("cluster_r_all_mean_facet_sex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")
```

```{r, fig.width = 5, fig.asp = 0.5}
report_main_effect("in_r_mean")
#full comparison
report_inter_age_sex_layer("in_r_mean")
```

# out_r_mean
```{r,fig.width = 4, fig.asp = 0.5, echo = FALSE}
#Facet by layer
plot_raw_boot_facet_layer ("out_r_mean",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(-0.2, 1), 
                            #legend_position = c(0.4, 0.8)
                            legend_position = "none")

#ggsave("cluster_r_all_mean_facet_layer.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")

#Facet by sex
plot_raw_boot_facet_sex ("out_r_mean",
                          y_breaks = c(1:6 * 0.2), 
                          y_limits = c(-0.2, 1), 
                          #legend_position = c(0.2, 0.8),
                          legend_position = "none")

#ggsave("cluster_r_all_mean_facet_sex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")
```

```{r, fig.width = 5, fig.asp = 0.5}
report_main_effect("out_r_mean")
#full comparison
report_inter_age_sex_layer("out_r_mean")
```

# r_diff
```{r,fig.width = 4, fig.asp = 0.5, echo = FALSE}
#Facet by layer
plot_raw_boot_facet_layer ("r_diff",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(0, 1), 
                            #legend_position = c(0.4, 0.8)
                            legend_position = "none")

#ggsave("cluster_r_all_mean_facet_layer.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")

#Facet by sex
plot_raw_boot_facet_sex ("r_diff",
                          y_breaks = c(1:6 * 0.2), 
                          y_limits = c(0, 1), 
                          #legend_position = c(0.2, 0.8),
                          legend_position = "none")

#ggsave("cluster_r_all_mean_facet_sex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")
```

```{r, fig.width = 5, fig.asp = 0.5}
report_main_effect("r_diff")
#full comparison
report_inter_age_sex_layer("r_diff")
```

#plot r_diff based on value
```{r}
layer.label = c("Layer 2/3", "Layer 4")
names(layer.label) = c("2", "4")
sex.label = c("Female", "Male")
names(sex.label) = c("F", "M")

y_breaks = c(1:6 * 0.2)
y_limits = c(0, 1)
y_limits = "none"
#legend_position = c(0.4, 0.85)
legend_position = 'right'

```

```{r,fig.width = 8, fig.asp =1, echo=FALSE}

df_lite_fig = df_lite %>%
        select(subject_id, all_of(cv_list), in_r_mean, out_r_mean) %>%
        drop_na(out_r_mean)
        
ggplot(df_lite_fig, aes(x = out_r_mean,y = in_r_mean, color = f.age)) +
    geom_beeswarm(alpha = 0.5) +
    facet_grid(sex ~ f.layer, labeller = labeller(sex = sex.label)) + 
    #labs(x = "out_r_mean", y = "in_r_mean") +
    theme(legend.position = legend_position,
          legend.title = element_blank(),
          legend.text = element_text(color = "black", size  = "10"),
          panel.spacing = unit(0, "lines"),
          strip.background = element_blank(),
          #strip.background = element_rect(color = "black", linewidth = 1),
          strip.placement = ("outside"),
          strip.text = element_text(size = 10),
          axis.text.x = element_text(color = "black", size = "10"),
          axis.line.x.bottom = element_line (linewidth = 1/2),
          axis.text.y = element_text(color = "black", size = "10"),
          axis.line.y = element_line(linewidth = 1/2), 
          axis.ticks.x = element_blank(),
          plot.background = element_blank(),
          plot.margin = unit(c(0,0.5,1,0), 'cm'))
          
```


# zf_r_allpair_mean
```{r,fig.width = 4, fig.asp = 0.5, echo = FALSE}
#Facet by layer
plot_raw_boot_facet_layer ("zf_r_allpair_mean",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(0.2, 1), 
                            legend_position = "none")

#ggsave("FacetbyLayer.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")

#Facet by sex
plot_raw_boot_facet_sex ("zf_r_allpair_mean",
                          y_breaks = c(1:6 * 0.2), 
                          y_limits = c(0.2, 1), 
                          legend_position = "none")

#ggsave("FacetbySex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 5, height = 2.5, units = "in")

```

```{r, fig.width = 5, fig.asp = 0.5}
report_main_effect("zf_r_allpair_mean")
#full comparison
report_inter_age_sex_layer("zf_r_allpair_mean")
```



# zf_in_r_mean
```{r,fig.width = 4, fig.asp = 0.5, echo = FALSE}
#Facet by layer
plot_raw_boot_facet_layer ("zf_in_r_mean",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(0, 1), 
                            legend_position = "none")

#ggsave("FacetbyLayer.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")

#Facet by sex
plot_raw_boot_facet_sex ("zf_in_r_mean",
                          y_breaks = c(1:6 * 0.2), 
                          y_limits = c(0, 1), 
                          legend_position = "none")

#ggsave("FacetbySex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 5, height = 2.5, units = "in")

```




```{r, fig.width = 5, fig.asp = 0.5}
report_main_effect("zf_in_r_mean")
#full comparison
report_inter_age_sex_layer("zf_in_r_mean")
```



#zf_out_r_mean
```{r,fig.width = 5, fig.asp = 0.5, echo = FALSE}
#Facet by layer
plot_raw_boot_facet_layer ("zf_out_r_mean",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(0, 1), 
                          #legend_position = c(0.4, 0.85),
                            legend_position = "none")

#ggsave("n_cls.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")

#Facet by sex
plot_raw_boot_facet_sex ("zf_out_r_mean",
                          y_breaks = c(1:6 * 0.2), 
                          y_limits = c(0, 1), 
                          #legend_position = c(0.3, 0.8),
                          legend_position = "none")

#ggsave("FacetbySex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2, units = "in"
```

```{r, fig.width = 5, fig.asp = 0.5}
report_main_effect("zf_out_r_mean")
#full comparison
report_inter_age_sex_layer("zf_out_r_mean")
```



#zf_r_diff
```{r,fig.width = 5, fig.asp = 0.5, echo = FALSE}
#Facet by layer
plot_raw_boot_facet_layer ("zf_r_diff",
                            #y_breaks = c(1:6 * 0.2), 
                            y_limits = c(-0.2, 0.8), 
                          #legend_position = c(0.4, 0.85),
                            legend_position = "none")

#ggsave("n_cls.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")

#Facet by sex
plot_raw_boot_facet_sex ("zf_r_diff",
                          #y_breaks = c(1:6 * 0.2), 
                          y_limits = c(-0.2, 0.8), 
                          #legend_position = c(0.3, 0.8),
                          legend_position = "none")

#ggsave("FacetbySex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2, units = "in"
```

```{r, fig.width = 5, fig.asp = 0.5}
report_main_effect("zf_r_diff")
#full comparison
report_inter_age_sex_layer("zf_r_diff")
```

#plot in - out relationship
```{r}
layer.label = c("Layer 2/3", "Layer 4")
names(layer.label) = c("2", "4")
sex.label = c("Female", "Male")
names(sex.label) = c("F", "M")

y_breaks = c(1:6 * 0.2)
y_limits = c(0, 1)
y_limits = "none"
#legend_position = c(0.4, 0.85)
legend_position = 'right'
```
 
#for tetrac correlation 
```{r,fig.width = 8, fig.asp =0.5, echo=FALSE}

df_lite_fig = df_lite %>%
        select(subject_id, all_of(cv_list),in_r_mean, out_r_mean)%>%
        drop_na(out_r_mean) %>%
        gather (condition,r_value, in_r_mean : out_r_mean,factor_key=TRUE) %>%
        tidyr::unite(col = "set", c("subject_id", "f.layer", "location"), remove = FALSE)%>%
        tidyr::unite(col ="sex_layer", c("sex", "f.layer"), remove = FALSE)
 
ggplot(df_lite_fig,
    aes(x = factor(condition, levels = c("in_r_mean","out_r_mean")),
           y = r_value)) +
    geom_line(data = df_lite_fig, 
              aes(group = set, color = sex_layer), alpha = 0.5, linewidth = 0.5) +
    #geom_beeswarm(alpha = 0.5) +
    scale_x_discrete(labels = c("in", "out")) +
    facet_wrap(~f.age,ncol = 5) + 
    labs(x = "", y = "") +
    theme(legend.position = legend_position,
          legend.title = element_blank(),
          legend.text = element_text(color = "black", size  = "10"),
          panel.spacing = unit(0, "lines"),
          strip.background = element_blank(),
          #strip.background = element_rect(color = "black", linewidth = 1),
          #strip.placement = ("outside"),
          #strip.text = element_text(size = 10),
          axis.text.x = element_text(color = "black", size = "10"),
          axis.line.x.bottom = element_line (linewidth = 1/2),
          axis.text.y = element_text(color = "black", size = "10"),
          axis.line.y = element_line(linewidth = 1/2), 
          axis.ticks.x = element_blank(),
          plot.background = element_blank(),
          plot.margin = unit(c(0,0.5,1,0), 'cm'))+
          ggsci::scale_color_locuszoom()

```
#for Pearson correlation 
```{r,fig.width = 8, fig.asp =1, echo=FALSE}

df_lite_fig = df_lite %>%
        select(subject_id, all_of(cv_list),zf_in_r_mean, zf_out_r_mean)%>%
        drop_na(zf_out_r_mean) %>%
        gather (condition,r_value, zf_in_r_mean : zf_out_r_mean,factor_key=TRUE) %>%
        tidyr::unite(col = "set", c("subject_id", "f.layer", "location"), remove = FALSE)%>%
        tidyr::unite(col ="sex_layer", c("sex", "f.layer"), remove = FALSE)
 
ggplot(df_lite_fig,
    aes(x = factor(condition, levels = c("zf_in_r_mean","zf_out_r_mean")),
           y = r_value)) +
    geom_line(data = df_lite_fig, 
              aes(group = set, color = sex_layer), alpha = 0.5, linewidth = 0.5) +
    scale_x_discrete(labels = c("in", "out")) +
    facet_wrap(~f.age,ncol = 5) + 
    labs(x = "", y = "") +
    theme(legend.position = legend_position,
          legend.title = element_blank(),
          legend.text = element_text(color = "black", size  = "10"),
          panel.spacing = unit(0, "lines"),
          strip.background = element_blank(),
          #strip.background = element_rect(color = "black", linewidth = 1),
          #strip.placement = ("outside"),
          #strip.text = element_text(size = 10),
          axis.text.x = element_text(color = "black", size = "10"),
          axis.line.x.bottom = element_line (linewidth = 1/2),
          axis.text.y = element_text(color = "black", size = "10"),
          axis.line.y = element_line(linewidth = 1/2), 
          axis.ticks.x = element_blank(),
          plot.background = element_blank(),
          plot.margin = unit(c(0,0.5,1,0), 'cm'))+
          ggsci::scale_color_locuszoom()


```