---
title: "Develop_Kmean_CovM--Facet Sex"
output: html_document
date: "2023-08-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

freshr::freshr()
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
library(ggpubr)
theme_set (theme_classic(base_size = 10, base_family = "sans"))

##libraries for color
library(ggsci)
```

```{r}
library(here)
load (here("output","2023-02-19_SummaryDevAll_Kmean_CovM_withCorr_Dist_20230113.RData"))
```

```{r}
##extract the replicates and assign attributes and class -------

boot_model_extract = function(x) {
  # extract lmeresamp objects
  mod = case_boot_list[[x]]
  #mod = residual_boot_list[[x]]
 
   # save replicates
  mod_rep = mod$replicates
  
  # keep complete cases
  mod_rep = mod_rep[complete.cases(mod_rep), ]
  
  # assign attributes and class to the replicates
  attr(mod_rep, "original_model") = mod$model
  class(mod_rep) = append(class(mod_rep), "bootstrap_model")
  class(mod_rep) = append(class(mod_rep), "see_bootstrap_model")
  
  # return replicates
  return(mod_rep)
}

##extract the replicates and assign attributes and class -------
 # boot model extract raw function returns two data frames for plotting figure: 
 # (1) boot sample and (2) original data

boot_model_extract_raw = function(x) {
  # extract lmeresamp objects
  mod = case_boot_list[[x]]
 
  # save replicates
  mod_rep = mod$replicates
  
  # save original datas
  mod_data = mod$model@frame
  
  # keep complete cases
  mod_rep = mod_rep[complete.cases(mod_rep), ]
  
  # assign attributes and class to the replicates
  attr(mod_rep, "original_model") = mod$model
  class(mod_rep) = append(class(mod_rep), "bootstrap_model")
  class(mod_rep) = append(class(mod_rep), "see_bootstrap_model")
  
  # return replicates
  return(list(mod_rep, mod_data))
}

```



```{r}
plot_raw_boot_facet_layer = function(x, var_name = x,title = x,
                                     y_breaks = c(1:6 * 0.2), 
                                     y_limits = c(0, 1), 
                                     legend_position = c(0.4, 0.85)) {
  # define label
  layer.label = c("Layer 2/3", "Layer 4")
  names(layer.label) = c("2", "4")
  
  # extract replicates
  mod_boot = boot_model_extract_raw(x)[[1]]
  
  # extract data
  mod_data = boot_model_extract_raw(x)[[2]]
  
  mod_data$yvar = mod_data[, x]
  mod_data$xvar = mod_data$f.age
  mod_data$tvar = mod_data$sex
  emm_plot = emmip(mod_boot, sex ~ f.age |f.layer, CIs = TRUE, 
                         CIarg = list(lwd = 1, alpha = 1), 
                         dodge = 0.5,linewidth = 0.5) + 
    geom_beeswarm(data = mod_data, dodge.width = 0.5,alpha = 0.7,
                  shape = 1, size = 1) +
    scale_y_continuous(breaks = y_breaks, limits = y_limits) +
    #facet_wrap(~ f.layer, labeller = labeller(f.layer =layer.label),
    #          strip.position = "bottom", nrow = 2, scale = "free") +
    facet_wrap(~ f.layer, labeller = labeller(f.layer =layer.label),
               strip.position = "bottom") +
    
    ggtitle(title) +
    labs(x = "", y= "", color = "Sex")+
    theme(strip.text = element_text(size = 10), 
        strip.background = element_blank(),
        #strip.background = element_rect(color = "black", linewidth = 1), 
        strip.placement = ("outside"),
        legend.text = element_text(color = "black", size  = "10"),
        legend.position = legend_position, legend.title = element_blank(),
        axis.text.x = element_text(color = "black", size = "10"),
        axis.line.x.bottom = element_line (linewidth = 1/2),
        axis.text.y = element_text(color = "black", size = "10"),
        axis.line.y = element_line(linewidth = 1/2), 
        axis.ticks.x = element_blank(),
        plot.background = element_blank(),
        plot.margin = unit(c(0,-0.1,0,0), 'cm')) + 
    scale_color_nejm() ->p
  
  return (p)
  
}

##plot raw data and bootstrapping result -Facet by sex ------------------

plot_raw_boot_facet_sex = function(x, var_name = x, title = x,
                                       y_breaks = c(1:6 * 0.2), 
                                       y_limits = c(0, 1), 
                                       legend_position = c(0.4, 0.85)){
  # define label
  sex.label = c("Female", "Male")
  names(sex.label) = c("F", "M")
  
  # extract replicates
  mod_boot = boot_model_extract_raw(x)[[1]]
  
  # extract data
  mod_data = boot_model_extract_raw(x)[[2]]
  
  mod_data$yvar = mod_data[, x]
  mod_data$xvar = mod_data$f.age
  mod_data$tvar = mod_data$f.layer 
  emm_plot = emmip(mod_boot, f.layer ~ f.age | sex, CIs = TRUE, 
                       CIarg = list(lwd = 1, alpha = 1), 
                       dodge = 0.5, linewidth = 0.5) +
    geom_beeswarm(data = mod_data, dodge.width = 0.5, alpha = 0.7,
                  shape = 1, size = 1)+
    scale_y_continuous(breaks = y_breaks, limits = y_limits)+
    facet_wrap(~ sex, labeller = labeller(sex =sex.label),
               strip.position = "bottom", nrow = 2, scale = "free") +
    ggtitle(title) +
    labs(x = "",y = "", color = "Layer") +
    theme(strip.text = element_text(size = 10), 
          strip.background = element_blank(),
          #strip.background = element_rect(color = "black", linewidth = 1), 
          strip.placement = ("outside"),
          legend.text = element_text(color = "black", size  = "10"),
          legend.position = legend_position, legend.title = element_blank(),
          axis.text.x = element_text(color = "black", size = "10"),
          axis.line.x.bottom = element_line (linewidth = 1/2),
          axis.text.y = element_text(color = "black", size = "10"),
          axis.line.y = element_line(linewidth = 1/2), 
          axis.ticks.x = element_blank(),
          plot.background = element_blank(),
          plot.margin = unit(c(0,-0.1,0,0), 'cm')) ->p
    
  return (p)
}
```


# silhs_mean_before_stat 
```{r,fig.width = 4, fig.asp = 0.5}

plot_raw_boot_facet_layer ("silhs_mean_before_stat",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(0, 0.6),
                            title = "",
                            legend_position = "none" )

ggsave("silhs_mean_before_stat_facet_layer.svg", plot = last_plot(), path =here("output_plot"),
      width = 4, height = 2.5, units = "in")


#ggarrange(a, b, ncol = 2, nrow = 1)

#ggsave("silhs_mean_before_stat.svg", plot = last_plot(), path =here("output_plot"),
 #      width = 4, height = 5, units = "in")

```

```{r}
#Facet by sex
plot_raw_boot_facet_sex ("silhs_mean_before_stat",
                          y_breaks = c(1:6 * 0.2), 
                          y_limits = c(0, .6),
                          title = "",
                          legend_position = "none")

ggsave("silhs_mean_before_stat.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 4.5, units = "in")
```



# subnetwork number
```{r,fig.width = 5, fig.asp = 0.5}
plot_raw_boot_facet_sex ("n_cls",
                            y_breaks = c(1:6 * 3), 
                            y_limits = c(0, 15), 
                           title= "",
                            legend_position = "none")

ggsave("n_cls.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 4.5, units = "in")

```



# Cell not in subnetwork
```{r,fig.width = 2, fig.asp = 2.5}
#Facet by layer
plot_raw_boot_facet_sex ("cells_not_in_assembly",
                            y_breaks = c(1:6 * 20), 
                            y_limits = c(0, 100), 
                            title = "",
                            legend_position = "none")

ggsave("cells_not_in_assembly.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 4.5, units = "in")

#Facet by sex
#plot_raw_boot_facet_sex ("cells_not_in_assembly",
#                          y_breaks = c(1:6 * 20), 
#                          y_limits = c(0, 100), 
#                          legend_position = c(0.3, 0.8))

#ggsave("FacetbySex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2, units = "in")
```

# Cell in single subnetwork
```{r,fig.width = 2, fig.asp = 2.5}
#Facet by layer
plot_raw_boot_facet_sex ("cells_in_one_assembly",
                            y_breaks = c(1:6 * 20), 
                            y_limits = c(0, 100), 
                            title = "",
                           legend_position = "none")

ggsave("cells_in_one_assembly.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 4.5, units = "in")

#Facet by sex
#plot_raw_boot_facet_sex ("cells_in_one_assembly",
#                          y_breaks = c(1:6 * 20), 
#                          y_limits = c(0, 100), 
#                          legend_position = c(0.3, 0.8))

#ggsave("FacetbySex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 5, height = 2.5, units = "in")
```



# Cell in many subnetwork
```{r,fig.width = 2, fig.asp = 2.5}
#Facet by layer
plot_raw_boot_facet_sex ("cells_in_many_assembly",
                            y_breaks = c(1:6 * 20), 
                            y_limits = c(0, 100), 
                            title = "",
                            legend_position = "none")

ggsave("cells_in_many_assembly.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 4.5, units = "in")

#Facet by sex
#plot_raw_boot_facet_sex ("cells_in_many_assembly",
#                          y_breaks = c(1:6 * 20), 
#                          y_limits = c(0, 100), 
#                          legend_position = c(0.3, 0.8))

#ggsave("FacetbySex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 5, height = 2.5, units = "in")
```




# r_allpair_mean
```{r,fig.width = 4, fig.asp = 0.5}
#Facet by layer
plot_raw_boot_facet_sex ("r_allpair_mean",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(0.2, 1), 
                            #legend_position = c(0.4, 0.85)
                            legend_position = "none")

ggsave("r_allpair_mean.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 4.5, units = "in")

#Facet by sex
#plot_raw_boot_facet_sex ("r_allpair_mean",
#                          y_breaks = c(1:6 * 0.2), 
#                          y_limits = c(0.2, 1), 
#                          #legend_position = c(0.3, 0.8),
#                          legend_position = "none")

ggsave("r_allpair_mean-facetSex.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.5, units = "in")
```



# cluster_r_all_mean
```{r,fig.width = 4, fig.asp = 0.5}
#Facet by layer
plot_raw_boot_facet_sex ("cluster_r_all_mean",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(0.2, 1), 
                            #legend_position = c(0.4, 0.8)
                            legend_position = "none")

ggsave("cluster_r_all_mean.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 4.5, units = "in")

#Facet by sex
#plot_raw_boot_facet_sex ("cluster_r_all_mean",
#                          y_breaks = c(1:6 * 0.2), 
#                          y_limits = c(0.2, 1), 
                          #legend_position = c(0.2, 0.8),
#                          legend_position = "none")

#ggsave("cluster_r_all_mean_facet_sex.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 2.5, units = "in")
```



# r_zf_allpair_mean
```{r,fig.width = 4, fig.asp = 0.5}
#Facet by sex
plot_raw_boot_facet_sex ("r_zf_allpair_mean",
                          y_breaks = c(1:6 * 0.2), 
                          y_limits = c(0.2, 1),
                          title = "",
                          legend_position = "none")

ggsave("r_zf_allpair_mean_sex.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 4.5, units = "in")

```



# cluster_r_zf_all_mean
```{r,fig.width = 4, fig.asp = 0.5}

plot_raw_boot_facet_sex ("cluster_r_zf_all_mean",
                            y_breaks = c(1:6 * 0.2), 
                            y_limits = c(0.2, 1),
                            title = "",
                            legend_position = "none")

ggsave("cluster_r_zf_all_mean_layer.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 4.5, units = "in")


```



# neuron_centroid
```{r,fig.width = 2, fig.asp = 2.5}
#Facet by layer
plot_raw_boot_facet_sex ("neuron_centroid",
                            y_breaks = c(1:6 * 50), 
                            y_limits = c(0, 200),
                            title = "",
                            legend_position = "none" )

ggsave("neuron_centroid.svg", plot = last_plot(), path =here("output_plot"),
      width = 2.5, height = 4.5, units = "in")


#ggarrange(a, b, ncol = 2, nrow = 1)

#ggsave("neuron_centroid.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 5, units = "in")

```


# pw_neuron_neuron
```{r,fig.width = 2, fig.asp = 2.5}
#Facet by layer
plot_raw_boot_facet_sex ("pw_neuron_neuron",
                            y_breaks = c(1:6 * 100), 
                            y_limits = c(0, 300),
                            title = "",
                            legend_position = "none" )

ggsave("pw_neuron_neuron.svg", plot = last_plot(), path =here("output_plot"),
      width = 2.5, height = 4.5, units = "in")


#ggarrange(a, b, ncol = 2, nrow = 1)

#ggsave("neuron_centroid.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 5, units = "in")

```


# centroid_centroid
```{r,fig.width = 2, fig.asp = 2.5}
#Facet by layer
plot_raw_boot_facet_sex ("centroid_centroid",
                            y_breaks = c(1:6 * 100), 
                            y_limits = c(0, 400),
                           title = "",
                            legend_position = "none" )

ggsave("centroid_centroid.svg", plot = last_plot(), path =here("output_plot"),
      width = 2.5, height = 4.5, units = "in")


#ggarrange(a, b, ncol = 2, nrow = 1)

#ggsave("neuron_centroid.svg", plot = last_plot(), path =here("output_plot"),
#       width = 4, height = 5, units = "in")

```

