---
title: "Figure 1 and Figure Supp1"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = NA)

freshr::freshr()
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set (theme_classic(base_size = 10, base_family = "sans"))

##libraries for color
library(ggsci)
library(wesanderson)
#names(wes_palettes)
library(colorBlindness)
library(viridis)
#dependent function
library(here)
source (here("src", "Develop_Function_posthoc_20230219.R"))

```

##### Figure 1D (Event frequency)
```{r}
#result source
load (here("output","2023-02-19_SummaryDevAll_basicParameter_MeanVersion_withCorr_20230113.RData"))
```

```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_sex ("event_freq",
                           y_breaks = c(1:6 * 1), 
                           y_limits = c(0, 3), 
                           legend_position = "right",
                           title = "") 
```

```{r}
report_main_effect("event_freq")
report_inter_age_sex_layer("event_freq")
```


##### Figure 1F (Synchrony frequency)
````{r, fig.width = 5, fig.asp = 0.5,echo=FALSE}
plot_raw_boot_facet_sex ("synchrony_freq",
                         y_breaks = c(1:6 * 1), 
                         y_limits = c(0, 3),
                         legend_position = "right",
                         title = "")
```

```{r}
report_main_effect("synchrony_freq")
report_inter_age_sex_layer("synchrony_freq")
```


##### Figure Supp1G (Pearson correlation coefficient)
```{r}
#result source
load (here("output","2024-01-11_SummaryDevAll_Kmean_CovM_Corr_in_outV2_20231204.RData"))
```

````{r, fig.width = 5, fig.asp = 0.5,echo=FALSE}
plot_raw_boot_facet_sex ("zf_r_allpair_mean",
                         y_breaks = c(1:6 * 0.2), 
                         y_limits = c(0.2, 1),
                         legend_position = "right",
                         title = "")
```

```{r}
report_main_effect("zf_r_allpair_mean")
report_inter_age_sex_layer("zf_r_allpair_mean")
```


