---
title: "Figure 2 and Figure Supp3"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = "")

freshr::freshr()
library(readxl)
library(janitor)
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
library(DT)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set (theme_classic(base_size = 10, base_family = "sans"))

##libraries for color
library(ggsci)
library(wesanderson)
#names(wes_palettes)
library(colorBlindness)
library(viridis)
#dependent function
library(here)
source (here("src", "Develop_Function_posthoc_20240411.R"))
```


##### Figure 2D (Silhouette value)
```{r}
#result source
load (here("output","SummaryDevAll_Kmean_CovM_withCorrDistArea.RData"))
```

```{r, fig.width = 3, fig.asp = 0.75, echo=FALSE}
plot_raw_boot_facet_layer_2age ("silhs_mean_before_stat",
                           y_breaks = seq(0,6, by= 0.2), 
                           y_limits = c(0, 0.6), 
                           legend_position = "right",
                           title = "") 

ggsave("silh.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 2.8, units = "in")
```

```{r}
report_main_effect("silhs_mean_before_stat")
report_inter_age_sex_layer("silhs_mean_before_stat")
```


##### Figure 2E (subnetwork #)
````{r, fig.width = 5, fig.asp = 0.5,echo=FALSE}
plot_raw_boot_facet_layer_2age("n_cls",
                         y_breaks = seq(0,15, by=3), 
                         y_limits = c(0, 15),
                         legend_position = "right",
                         title = "")
ggsave("ncl.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 2.8, units = "in")
````



```{r}
report_main_effect("n_cls")
report_inter_age_sex_layer("n_cls")
```


### Figure Supp 3C- tCC in- and out- subnetwork

```{r,fig.width = 8, fig.asp =0.4, echo=FALSE}

layer.label = c("Layer 2/3", "Layer 4")
names(layer.label) = c("2", "4")

age.label = c("P11", "P21")
names(age.label) = c("11","21")


df_lite_fig = df_lite %>%
        filter (f.age != 13)%>%
        filter (f.age != 15)%>%
        filter(f.age !=18)%>%
        select(subject_id, sex, f.layer, f.age,location,in_r_mean, out_r_mean)%>%
        drop_na(out_r_mean) %>%
        gather (condition,r_value, in_r_mean : out_r_mean,factor_key=TRUE) %>%
        tidyr::unite(col = "set", c("subject_id", "f.layer", "location"), remove = FALSE)%>%
        tidyr::unite(col ="sex_layer", c("sex", "f.layer"), remove = FALSE)
 
ggplot(df_lite_fig,
    aes(x = factor(condition, levels = c("in_r_mean","out_r_mean")),
           y = r_value)) +
    geom_line(data = df_lite_fig, 
              aes(group = set, color = sex_layer), alpha = 0.5, linewidth = 0.5) +
    scale_x_discrete(labels = c("in", "out")) +
    scale_y_continuous(breaks = seq(-0.4, 2, by = 0.2), limits = c(-0.2, 1)) + 
    facet_wrap(~f.age,ncol = 5, labeller = labeller(f.age = age.label)) +
    labs(x = "", y = "") +
    theme(legend.position = "left",
          legend.title = element_blank(),
          legend.text = element_text(color = "black", size  = "10"),
          #panel.border = element_rect(color = "black", fill = NA, size = 0.5),
          panel.spacing = unit(0, "lines"),
          strip.background = element_blank(),
          #strip.placement = ("outside"),
          #strip.text = element_text(size = 10),
          axis.text.x = element_text(color = "black", size = "10"),
          axis.line.x.bottom = element_line (linewidth = 1/2),
          axis.text.y = element_text(color = "black", size = "10"),
          axis.line.y = element_line(linewidth = 1/2), 
          axis.ticks.x = element_blank(),
          plot.background = element_blank(),
          plot.margin = unit(c(0,0.5,0,0), 'cm'))+
          ggsci::scale_color_locuszoom()+
          annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf)


ggsave("r_in_vs_out.svg", plot = last_plot(), path =here("output_plot"),
       width =4, height = 2.5, units = "in")

```


##### Figure 2F (tetrachoric correlation-in the same subnetwork)
````{r, fig.width = 5, fig.asp = 0.5,echo=FALSE}
plot_raw_boot_facet_layer_2age("in_r_mean",
                         y_breaks = seq(0,6, by=0.2), 
                         y_limits = c(0.2, 1),
                         legend_position = "right",
                         title = "")
ggsave("in_r_mean.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.5, height = 2.8, units = "in")
````

```{r}
report_main_effect("in_r_mean")
report_inter_age_sex_layer("in_r_mean")
```


### Figure Supp 3D - neuronal number vs subnetwork number
```{r}
#import data
df = read_xlsx(
  here("data", "Kmean_CovM_neuronN_time.xlsx"),
  sheet = "ForMultilevel")

# check column names
df = clean_names(df)
# list of response variables
rv_list = c("total_cell_number", "time_interval","n_cls")
rv_list = tolower(rv_list)
cv_list= c("sex", "age", "layer", "location")

cv_list[2]= "f.age"
cv_list[3]="f.layer"

# create a lite version including rv_list and cv_list
df_lite = df %>%
  filter(location != 4) %>%
  mutate (f.age = factor(age), f.layer = factor(layer))%>%
  filter (f.age != 13)%>%
  filter (f.age != 15)%>%
  filter(f.age !=18)%>%
  select(subject_id, all_of(cv_list), all_of(rv_list))

```

```{r,fig.width = 4, fig.asp =0.5, echo=FALSE}
df_lite_fig = df_lite %>%
        select(subject_id,all_of(cv_list), total_cell_number,n_cls)%>%
        drop_na(n_cls) %>%
        tidyr::unite(col ="sex_layer", c("sex", "f.layer"), remove = FALSE)

layer.label = c("Layer 2/3", "Layer 4")
names(layer.label) = c("2", "4")
sex.label = c("Female", "Male")
names(sex.label) = c("F", "M")
age.label = c("P11", "P21")
names(age.label) = c("11", "21")

ggplot(df_lite_fig,
    aes(x = n_cls, y = total_cell_number, color = sex_layer)) +
    geom_point(shape =1,alpha = 1)+
    facet_wrap(~f.age, ncol = 2, labeller = labeller(f.age = age.label), strip.position = "top") + 
    scale_x_continuous(breaks = c(1:5 * 5), limits =  c(0, 15)) +
    scale_y_continuous(breaks = c(1:6 * 100), limits =  c(0, 400)) +
    labs(x = "subnetwork #", y = "neuronal #") +
    theme(legend.position = "right",
          legend.title = element_blank(),
          legend.text = element_text(color = "black", size  = "10"),
          strip.placement = "outside",
          strip.text = element_text(color = "black", size  = "10"),
          strip.background = element_blank(),
          axis.text.x = element_text(color = "black", size = "10"),
          axis.line.x.bottom = element_line (linewidth = 1/4),
          axis.ticks.length.x = unit(-0.1, "cm"),
          axis.text.y = element_text(color = "black", size = "10"),
          axis.line.y = element_line(linewidth = 1/4),
          plot.background = element_blank()) + 
   ggsci::scale_color_locuszoom() +
   annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf)
   
ggsave("ncls_vs_neuronalN.svg", plot = last_plot(), path =here("output_plot"),
      width = 3, height = 2, units = "in")

```


```{r}
shapiro.test(df_lite_fig$n_cls)
shapiro.test(df_lite_fig$total_cell_number)
## when p-value < 0.05 --> data are not normal distributed
#if the data are not normally distributed, it’s recommended to use the non-parametric correlation, including Spearman and Kendall rank-based correlation tests.
cor.test(df_lite_fig$n_cls, df_lite_fig$total_cell_number,
            method = "spearman")

```


### Figure Supp 3E - time vs subnetwork number
```{r,fig.width = 4, fig.asp =0.5, echo=FALSE}

df_lite_fig = df_lite %>%
        select(subject_id,all_of(cv_list), time_interval,n_cls)%>%
        drop_na(n_cls) %>%
        tidyr::unite(col ="sex_layer", c("sex", "f.layer"), remove = FALSE)

layer.label = c("Layer 2/3", "Layer 4")
names(layer.label) = c("2", "4")
sex.label = c("Female", "Male")
names(sex.label) = c("F", "M")
age.label = c("P11", "P21")
names(age.label) = c("11", "21")
 
ggplot(df_lite_fig,
    aes(x = n_cls, y = time_interval, color = sex_layer)) +
    geom_point(shape =1,alpha = 1)+
    facet_wrap(~f.age, ncol = 5, labeller = labeller(f.age = age.label), strip.position = "top") + 
    scale_x_continuous(breaks = c(1:5 * 5), limits =  c(0, 15)) +
    scale_y_continuous(breaks = c(1:6 * 100), limits =  c(0, 300)) +
    labs(x = "subnetwork #", y = "time (s)") +
    theme(legend.position = "right",
          legend.title = element_blank(),
          legend.text = element_text(color = "black", size  = "10"),
          strip.placement = "outside",
          strip.text = element_text(color = "black", size  = "10"),
          strip.background = element_blank(),
          axis.text.x = element_text(color = "black", size = "10"),
          axis.line.x.bottom = element_line (linewidth = 1/4),
          axis.ticks.length.x = unit(-0.1, "cm"),
          axis.text.y = element_text(color = "black", size = "10"),
          axis.line.y = element_line(linewidth = 1/4),
          plot.background = element_blank()) + 
   ggsci::scale_color_locuszoom() +
   annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf)
    
ggsave("ncls_vs_time.svg", plot = last_plot(), path =here("output_plot"),
       width = 3, height = 2, units = "in")

```


```{r}
shapiro.test(df_lite_fig$time_interval)

cor.test(df_lite_fig$n_cls, df_lite_fig$time_interval, method = "pearson")

cor.test(df_lite_fig$n_cls, df_lite_fig$time_interval, method = "spearman")

```


