---
title: "Figure 1 and Figure Supp2"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, comment = "")

freshr::freshr()
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set (theme_classic(base_size = 10, base_family = "sans"))
library(DT)

##libraries for color
library(ggsci)
library(wesanderson)
#names(wes_palettes)
library(colorBlindness)
library(viridis)
#dependent function
library(here)
source (here("src", "Develop_Function_posthoc_20240411.R"))
```


##### Figure 1D (Event frequency)
```{r}
#result source
load (here("output","SummaryDevAll_basicParameter.RData"))
```

```{r, fig.width = 3, fig.asp = 0.75, echo=FALSE}
plot_raw_boot_facet_layer_2age ("event_freq",
                           y_breaks = seq(0, 6 , by=1),
                           y_limits = c(0, 3), 
                           legend_position = "right",
                           title = "")
ggsave("event_freq.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.4, height = 2.6, units = "in")
```

```{r}
report_main_effect("event_freq")
report_inter_age_sex_layer("event_freq")
```


##### Figure 1F (Synchrony frequency)
```{r, fig.width = 3, fig.asp = 0.75, echo=FALSE}
plot_raw_boot_facet_layer_2age ("synchrony_freq",
                           y_breaks = seq (0,6, by= 1), 
                           y_limits = c(0, 4), 
                           legend_position = "right",
                           title = "")
ggsave("sync_freq.svg", plot = last_plot(), path =here("output_plot"),
       width = 2.4, height = 2.6, units = "in")
```

```{r}
report_main_effect("synchrony_freq")
report_inter_age_sex_layer("synchrony_freq")
```


##### Figure Supp2F (Pearson correlation coefficient)
```{r}
#result source
load (here("output","SummaryDevAll_Kmean_CovM_withCorrDistArea.RData"))
```

```{r, fig.width = 3, fig.asp = 0.75, echo=FALSE}
plot_raw_boot_facet_layer_2age ("zf_r_allpair_mean",
                           y_breaks = seq(0.2, 1 , by=0.2),
                           y_limits = c(0.2,1), 
                           legend_position = "",
                           title = "")
ggsave("zf_r_allpair_mean2age.svg", plot = last_plot(), path =here("output_plot"),
       width = 3.2, height = 3.2, units = "in")
```

```{r}
report_main_effect("zf_r_allpair_mean")
report_inter_age_sex_layer("zf_r_allpair_mean")
```


##### Figure Supp2G (Mutual information)
```{r}
load (here("output","SummaryDevAll_Kmean_CovM_MI_Corr.RData"))
```

```{r,fig.width = 3, fig.asp = 0.75, echo=FALSE}
plot_raw_boot_facet_layer_2age ("zf_r_allpair_mean",
                           y_breaks = seq(0, 2 , by=0.4),
                           y_limits = c(0,1.2), 
                           legend_position = "right",
                           title = "")
ggsave("MI_zf_r_allpair_mean2age.svg", plot = last_plot(), path =here("output_plot"),
       width = 3.2, height = 3.2, units = "in")
```

```{r}
report_main_effect("zf_r_allpair_mean")
report_inter_age_sex_layer("zf_r_allpair_mean")
```


