---
title: "Develop_FGFRcKO_Kmean_CovM"
output:
  html_document: default
  pdf_document: default
date: "2023-08-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

freshr::freshr()
library(here)
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
library(pbkrtest)
library(lme4)
library(lmeresampler)
library(ggpubr)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set(theme_bw())
theme_set (theme_classic(base_size = 10, base_family = "sans"))
```

```{r}
source (here("src", "Develop_FGFRcKO_Function_posthoc_20230727.R"))
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Kmean_CovM_20230104.RData.RData"))
```


##figure
```{r, fig.width = 8, fig.asp = 1, echo=FALSE}

a <- plot_raw_boot_facet_layer ("silhs_mean_before_stat",
                           y_breaks = c(1:8 * 0.2), 
                           y_limits = c(0, 0.8), 
                           legend_position = "none")

b <- plot_raw_boot_facet_layer  ("n_cls",
                           y_breaks = c(1:6 * 3), 
                           y_limits = c(0, 15), 
                           legend_position = "none")

c <-plot_raw_boot_facet_layer  ("cells_not_in_assembly",
                           y_breaks = c(1:6 * 20), 
                           y_limits = c(0, 100), 
                           legend_position = c(0.4, 0.85)) 

d <- plot_raw_boot_facet_layer  ("cells_in_one_assembly",
                           y_breaks = c(1:6 * 20), 
                           y_limits = c(0, 100), 
                           legend_position = "none") 

e <- plot_raw_boot_facet_layer  ("cells_in_many_assembly",
                           y_breaks = c(1:6 * 20), 
                           y_limits = c(0, 100), 
                           legend_position = c(0.4, 0.85))


ggarrange(a,b,
          c, d,
          e,
          ncol = 2, nrow = 3)
#ggsave("centroid_centroid.svg", plot = last_plot(), path =here("output_plot"),
#      width = 3.8, height = 2.5, units = "in")
```


##figure
```{r, fig.width = 8, fig.asp = 1.4, echo=FALSE}

f <- plot_raw_boot_facet_layer  ("r_allpair_mean",
                           y_breaks = c(1:20 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = c(0.4, 0.85)) 
        
g <-plot_raw_boot_facet_layer  ("cluster_r_all_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = 'none')

h <- plot_raw_boot_facet_layer  ("r_zf_allpair_mean",
                           y_breaks = c(1:10 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = "none") 
        
i <-  plot_raw_boot_facet_layer  ("cluster_r_zf_all_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = "none") 
        
j <-plot_raw_boot_facet_layer  ("neuron_centroid",
                           y_breaks = c(1:6 * 50), 
                           y_limits = c(0, 200), 
                           legend_position = "none") 
              
k <- plot_raw_boot_facet_layer  ("pw_neuron_neuron",
                           y_breaks = c(1:6 * 100), 
                           y_limits = c(0, 300), 
                           legend_position = "none") 
                
l <-plot_raw_boot_facet_layer ("centroid_centroid",
                           y_breaks = c(1:8 * 100), 
                           y_limits = c(0, 400), 
                           legend_position = "none")
ggarrange(f,g,
          h, i,
          j, k,
          l,
          ncol = 2, nrow = 4)
#ggsave("centroid_centroid.svg", plot = last_plot(), path =here("output_plot"),
#      width = 3.8, height = 2.5, units = "in")
```

# silhs_mean_before_stat
```{r}
report_main_effect("silhs_mean_before_stat")
report_group_int_layer("silhs_mean_before_stat")
#the most comprehensive comparison
report_inter_age_group_layer("silhs_mean_before_stat")
```


# n_cls
```{r}
report_main_effect("n_cls")
report_group_int_layer("n_cls")
#the most comprehensive comparison
report_inter_age_group_layer("n_cls")
```

# cells_not_in_assembly
```{r}
report_main_effect("cells_not_in_assembly")
report_group_int_layer("cells_not_in_assembly")
#the most comprehensive comparison
report_inter_age_group_layer("cells_not_in_assembly")
```

# cells_in_one_assembly
```{r}
report_main_effect("cells_in_one_assembly")
report_group_int_layer("cells_in_one_assembly")
#the most comprehensive comparison
report_inter_age_group_layer("cells_in_one_assembly")
```

#cells_in_many_assembly
```{r}
report_main_effect("cells_in_many_assembly")
report_group_int_layer("cells_in_many_assembly")
#the most comprehensive comparison
report_inter_age_group_layer("cells_in_many_assembly")
```


# r_allpair_mean
```{r}
report_main_effect("r_allpair_mean")
report_group_int_layer("r_allpair_mean")
#the most comprehensive comparison
report_inter_age_group_layer("r_allpair_mean")
```

# cluster_r_all_mean
```{r}
report_main_effect("cluster_r_all_mean")
report_group_int_layer("cluster_r_all_mean")
#the most comprehensive comparison
report_inter_age_group_layer("cluster_r_all_mean")
```


# r_zf_allpair_mean
```{r}
report_main_effect("r_zf_allpair_mean")
report_group_int_layer("r_zf_allpair_mean")
#the most comprehensive comparison
report_inter_age_group_layer("r_zf_allpair_mean")
```


#cluster_r_zf_all_mean
```{r}
report_main_effect("cluster_r_zf_all_mean")
report_group_int_layer("cluster_r_zf_all_mean")
#the most comprehensive comparison
report_inter_age_group_layer("cluster_r_zf_all_mean")
```

#neuron_centroid
```{r}
report_main_effect("neuron_centroid")
report_group_int_layer("neuron_centroid")
#the most comprehensive comparison
report_inter_age_group_layer("neuron_centroid")
```


##pw_neuron_neuron
```{r}
report_main_effect("pw_neuron_neuron")
report_group_int_layer("pw_neuron_neuron")
#the most comprehensive comparison
report_inter_age_group_layer("pw_neuron_neuron")
```


##centroid_centroid
```{r}
report_main_effect("centroid_centroid")
report_group_int_layer("centroid_centroid")
#the most comprehensive comparison
report_inter_age_group_layer("centroid_centroid")
```

