---
title: "Develop_FGFRcKO_Kmean_CovM_correlation_in_out"
output:
  html_document: default
  pdf_document: default
date: "2023-12-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

freshr::freshr()
library(here)
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
library(pbkrtest)
library(lme4)
library(lmeresampler)
library(ggpubr)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set(theme_bw())
theme_set (theme_classic(base_size = 10, base_family = "sans"))
```

```{r}
source (here("src", "Develop_FGFRcKO_Function_posthoc_20230727.R"))
load (here("output","2023-12-04_SummaryAll_FGFR-tri-cKO_Tetrac_Pearson_in_out_clusterV2_20231204.RData"))
```


##figure
```{r, fig.width = 8, fig.asp = 1, echo=FALSE}

a <- plot_raw_boot_facet_layer  ("r_allpair_mean",
                           y_breaks = c(1:20 * 0.2), 
                           y_limits = c(-0.6, 1), 
                           legend_position = "none") 
        
b <-plot_raw_boot_facet_layer  ("in_r_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = 'none')

c <- plot_raw_boot_facet_layer  ("out_r_mean",
                           y_breaks = c(1:10 * 0.2), 
                           y_limits = c(-0.8, 1), 
                           legend_position = "none") 
        
d <-  plot_raw_boot_facet_layer  ("r_diff",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(-0.2, 1), 
                           legend_position = "none") 
        
ggarrange(a,d,
          b, c,
          ncol = 2, nrow = 2)
#ggsave("centroid_centroid.svg", plot = last_plot(), path =here("output_plot"),
#      width = 3.8, height = 2.5, units = "in")
```

# r_allpair_mean
```{r}
report_main_effect("r_allpair_mean")
report_group_int_layer("r_allpair_mean")
#the most comprehensive comparison
report_inter_age_group_layer("r_allpair_mean")
```


# r_diff
```{r}
report_main_effect("r_diff")
report_group_int_layer("r_diff")
#the most comprehensive comparison
report_inter_age_group_layer("r_diff")
```

# in_r_mean
```{r}
report_main_effect("in_r_mean")
report_group_int_layer("in_r_mean")
#the most comprehensive comparison
report_inter_age_group_layer("in_r_mean")
```

# out_r_mean
```{r}
report_main_effect("out_r_mean")
report_group_int_layer("out_r_mean")
#the most comprehensive comparison
report_inter_age_group_layer("out_r_mean")
```



##figure
```{r, fig.width = 8, fig.asp = 1, echo=FALSE}

e <- plot_raw_boot_facet_layer  ("zf_r_allpair_mean",
                           y_breaks = c(1:20 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = "none") 
        
f <-plot_raw_boot_facet_layer  ("zf_in_r_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = 'none')

g <- plot_raw_boot_facet_layer  ("zf_out_r_mean",
                           y_breaks = c(1:10 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = "none") 
        
h <-  plot_raw_boot_facet_layer  ("zf_r_diff",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(-0.4, 1), 
                           legend_position = "none") 
        
ggarrange(e,h,
          f, g,
          ncol = 2, nrow = 2)
#ggsave("centroid_centroid.svg", plot = last_plot(), path =here("output_plot"),
#      width = 3.8, height = 2.5, units = "in")
```


#zf_r_allpair_mean
```{r}
report_main_effect("zf_r_allpair_mean")
report_group_int_layer("zf_r_allpair_mean")
#the most comprehensive comparison
report_inter_age_group_layer("zf_r_allpair_mean")
```


#zf_r_diff
```{r}
report_main_effect("zf_r_diff")
report_group_int_layer("zf_r_diff")
#the most comprehensive comparison
report_inter_age_group_layer("zf_r_diff")
```

# zf_in_r_mean
```{r}
report_main_effect("zf_in_r_mean")
report_group_int_layer("zf_in_r_mean")
#the most comprehensive comparison
report_inter_age_group_layer("zf_in_r_mean")
```

# zf_out_r_mean
```{r}
report_main_effect("zf_out_r_mean")
report_group_int_layer("zf_out_r_mean")
#the most comprehensive comparison
report_inter_age_group_layer("zf_out_r_mean")
```

