---
title: "Develop_FGFRcKO_basicParam_Freq"
output: html_document
date: "2023-08-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

freshr::freshr()
library(here)
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
library(pbkrtest)
library(lme4)
library(lmeresampler)
library(ggpubr)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set(theme_bw())
theme_set (theme_classic(base_size = 10, base_family = "sans"))
```

```{r}
source (here("src", "Develop_FGFRcKO_Function_posthoc_20230727.R"))
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Basic_Parameter_MeanVersion_withCorr_20230113.RData.RData"))
```

# generate figure
```{r, fig.width = 8, fig.asp =1.2, echo=FALSE}

a <-plot_raw_boot_facet_layer  ("event_freq",
                           y_breaks = c(1:6 * 1), 
                           y_limits = c(0, 4), 
                           legend_position = 'none') 

b <- plot_raw_boot_facet_layer  ("rcorr_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = 'none')

c <- plot_raw_boot_facet_layer  ("r_in_distance_before100_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = 'none') 

d <- plot_raw_boot_facet_layer  ("synchrony_freq",
                           y_breaks = c(1:6 * 1), 
                           y_limits = c(0, 4), 
                           legend_position = 'none') 

e <- plot_raw_boot_facet_layer  ("synchrony_peak",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 0.6), 
                           legend_position = 'none')


f <-plot_raw_boot_facet_layer  ("amp",
                           y_breaks = c(1:6 * 5), 
                           y_limits = c(0, 15), 
                           legend_position = 'none') 

g <-plot_raw_boot_facet_layer  ("duration",
                           y_breaks = c(1:6 * 50), 
                           y_limits = c(100, 300), 
                           legend_position = 'none') 

h <-plot_raw_boot_facet_layer  ("area",
                           y_breaks = c(1:6 * 5), 
                           y_limits = c(0, 30), 
                           legend_position = 'none') 


ggarrange(a,b,
          c,d,
          e,f,
          g,h,
          ncol = 2, nrow = 4)

#ggsave("All1.svg", plot = last_plot(), path =here("output_plot"),
#       width = 7.6, height = 7.5, units = "in")
```



# Event frequency
```{r}
report_main_effect("event_freq")
report_group_int_layer("event_freq")
#the most comprehensive comparison
report_inter_age_group_layer("event_freq")
```


#Pearson Corrleation mean
```{r}
report_main_effect("rcorr_mean")
report_group_int_layer("rcorr_mean")
#the most comprehensive comparison
report_inter_age_group_layer("rcorr_mean")
```


#Pearson Corrleation before100_mean
```{r}
report_main_effect("r_in_distance_before100_mean")
report_group_int_layer("r_in_distance_before100_mean")
#the most comprehensive comparison
report_inter_age_group_layer("r_in_distance_before100_mean")
```


# Synchrony Freq
```{r}
report_main_effect("synchrony_freq")
report_group_int_layer("synchrony_freq")
#the most comprehensive comparison
report_inter_age_group_layer("synchrony_freq")
```


#Synchrony peak
```{r}
report_main_effect("synchrony_peak")
report_group_int_layer("synchrony_peak")
#the most comprehensive comparison
report_inter_age_group_layer("synchrony_peak")
```

#Amplitude
```{r}
report_main_effect("amp")
report_group_int_layer("amp")
#report_inter_age_group_layer("ampi") ---> doesn't work
#report_inter_age_group_layer_V2("ampi") ---> still doesn't work
```

# Duration
```{r}
report_main_effect("duration")
report_group_int_layer("duration")
#the most comprehensive comparison
report_inter_age_group_layer("duration")
```


#Area
```{r}
report_main_effect("area")
report_group_int_layer("area")
#the most comprehensive comparison
report_inter_age_group_layer("area")
```

# IEI
````{r, fig.width = 5, fig.asp = 0.5}
plot_raw_boot_facet_layer  ("iei",
                           y_breaks = c(1:20 * 5000), 
                           y_limits = c(0, 15000), 
                           legend_position = c(0.4, 0.85)) 
        

#ggsave("IEI.svg", plot = last_plot(), path =here("output_plot"),
#      width = 3.8, height = 2.5, units = "in")

```

```{r}
report_main_effect("iei")
report_group_int_layer("iei")
#the most comprehensive comparison
report_inter_age_group_layer("iei")
```

