---
title: "Develop_FGFRcKO__Plot figure"
output: html_document
date: "2023-09-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

freshr::freshr()
library(here)
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
library(pbkrtest)
library(lme4)
library(lmeresampler)
library(ggpubr)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set(theme_bw())
theme_set (theme_classic(base_size = 10, base_family = "sans"))
```

```{r}
##defince function
# extract lm bootstrapped coefficients ------------------------------------

lm_boot_extract = function(x) {
  
  # extract simpleboot object
  mod = lm_boot_list[[x]]
  
  # extract bootstrapped coefs
  boot_ls = lapply(1:length(mod$boot.list), 
                   function(x) mod$boot.list[[x]]$coef)
  boot_rep = as.data.frame(do.call(rbind, boot_ls))
  
  # keep complete cases
  boot_rep = boot_rep[complete.cases(boot_rep), ]
  
  # assign attributes and class to the replicates
  attr(boot_rep, "original_model") = mod$orig.lm
  class(boot_rep) = append(class(boot_rep), "bootstrap_model")
  class(boot_rep) = append(class(boot_rep), "see_bootstrap_model")
  
  # return replicates
  return(boot_rep)
}


# extract the replicates and assign attributes and class ------------------

lmer_boot_extract = function(x) {
  # extract lmeresamp objects
  mod = case_boot_list[[x]]
  
  # save replicates
  boot_rep = mod$replicates
  
  # keep complete cases
  boot_rep = boot_rep[complete.cases(boot_rep), ]
  
  # assign attributes and class to the replicates
  attr(boot_rep, "original_model") = mod$model
  class(boot_rep) = append(class(boot_rep), "bootstrap_model")
  class(boot_rep) = append(class(boot_rep), "see_bootstrap_model")
  
  # return replicates
  return(boot_rep)
}


boot_model_extract_raw = function(x) {
  # extract replicates
  if (x %in% names(case_boot_list)) {
    boot_rep = lmer_boot_extract(x)
  } else {
    boot_rep = lm_boot_extract(x)
  }
  
  return(boot_rep)
}

##plot raw data and bootstrapping result -Facet by layer ------------------

plot_raw_boot_facet_layer = function(x, var_name = x,
                                     y_breaks = c(1:6 * 0.2), 
                                     y_limits = c(0, 1), 
                                     legend_position = "none") {
  # define label
  layer.label = c("Layer 2/3", "Layer 4")
  names(layer.label) = c("2", "4")
  
   # extract replicates
  mod_boot = boot_model_extract_raw(x)
  
  # use original data set instead
  # https://tibble.tidyverse.org/reference/subsetting.html
  # the subsetting behavior is somewhat different in tibbles lol
  df_lite$yvar = df_lite[, x, drop = TRUE]
 
  # marginal effect point estimates and CI 
  emms = emmip(mod_boot, group ~ f.age | f.layer, CIs = TRUE, plotit = FALSE)
  emm_plot = ggplot(emms, aes(x = f.age, y = yvar, color = group)) +
    geom_pointrange(aes(ymin = LCL, ymax = UCL), size = 1,
                    position = position_dodge (width =0.5),
                    shape = 16, fatten = 1) +
    geom_beeswarm(data = df_lite, dodge.width = 0.5, alpha = 0.7,
                  shape = 1, size = 1) +
    scale_y_continuous(breaks = y_breaks, limits = y_limits) +
    facet_wrap(~ f.layer,labeller = labeller(f.layer =layer.label),
               strip.position = "bottom") +
    labs(x = "", y= "", color = "group") +
    theme(strip.text = element_text(size = 10), 
          strip.background = element_blank(),
          strip.placement = ("outside"),
          legend.text = element_text(color = "black", size  = "10"),
          legend.position = legend_position, legend.title = element_blank(),
          axis.text.x = element_text(color = "black", size = "10"),
          axis.line.x.bottom = element_line (linewidth = 1/2),
          axis.text.y = element_text(color = "black", size = "10"),
          axis.line.y = element_line(linewidth = 1/2), 
          axis.ticks.x = element_blank(),
          plot.background = element_blank(),
          plot.margin = unit(c(0,0,0,0), 'cm'))+
    scale_color_d3() ->p
  
  return(p)
  
}
```

```{r}
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Basic_Parameter_MeanVersion_withCorr_20230113.RData.RData"))
```


# generate figure
```{r}
plot_raw_boot_facet_layer  ("synchrony_peak",
                           y_breaks = c(1:6 * 0.1 ), 
                           y_limits = c(0, 0.5), 
                           legend_position = 'none') 

ggsave("synchrony_peak.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")



plot_raw_boot_facet_layer  ("duration",
                           y_breaks = c(1:6 * 50), 
                           y_limits = c(100, 300), 
                           legend_position = 'none') 

ggsave("duration.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")


ggsave("synchrony_freq.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")



```

# generate figure
```{r}
plot_raw_boot_facet_layer  ("event_freq",
                           y_breaks = c(1:6 * 1 ), 
                           y_limits = c(0, 4), 
                           legend_position = 'none') 

ggsave("event_freq.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")



plot_raw_boot_facet_layer  ("synchrony_freq",
                           y_breaks = c(1:6 * 1), 
                           y_limits = c(0, 3), 
                           legend_position = 'none') 

ggsave("synchrony_freq.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")



```


```{r}
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Kmean_CovM_20230104.RData.RData"))
```


```{r}

plot_raw_boot_facet_layer  ("silhs_mean_before_stat",
                           y_breaks = c(1:6 * 0.2 ), 
                           y_limits = c(0, 1), 
                           legend_position = 'none')
ggsave("silhs_mean_before_stat.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")


plot_raw_boot_facet_layer  ("n_cls",
                           y_breaks = c(1:6 * 3), 
                           y_limits = c(0, 15), 
                           legend_position = 'none') 
ggsave("n_cls.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")


plot_raw_boot_facet_layer  ("r_allpair_mean",
                           y_breaks = c(1:6 * 0.4), 
                           y_limits = c(-1, 1), 
                           legend_position = 'none') 
ggsave("r_allpair_mean.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")


plot_raw_boot_facet_layer  ("cluster_r_all_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0,1.2), 
                           legend_position = 'none') 
ggsave("cluster_r_all_mean.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")


plot_raw_boot_facet_layer  ("r_zf_allpair_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = 'none') 

ggsave("r_zf_allpair_mean.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")


plot_raw_boot_facet_layer  ("cluster_r_zf_all_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = 'none') 
ggsave("cluster_r_zf_all_mean.svg", plot = last_plot(), path =here("output_plot"),
       width = 4, height = 2.2, units = "in")



```


```{r}
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Basic_Parameter_MeanVersion_withCorr_20230113.RData.RData"))
```



# generate figure
```{r}


a <-plot_raw_boot_facet_layer  ("event_freq",
                           y_breaks = c(1:6 * 1 ), 
                           y_limits = c(0, 4), 
                           legend_position = 'none') 


b <-plot_raw_boot_facet_layer  ("synchrony_freq",
                           y_breaks = c(1:6 * 1), 
                           y_limits = c(0, 3), 
                           legend_position = 'none') 


```


```{r}
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Kmean_CovM_20230104.RData.RData"))
```


# generate figure-supp
```{r}


a <-plot_raw_boot_facet_layer  ("synchrony_peak",
                           y_breaks = c(1:6 * 0.1), 
                           y_limits = c(0, 0.4), 
                           legend_position = 'none') 

b <-plot_raw_boot_facet_layer  ("amp",
                           y_breaks = c(1:6 * 3), 
                           y_limits = c(0,15), 
                           legend_position = 'none') 

c <-plot_raw_boot_facet_layer  ("duration",
                           y_breaks = c(1:6 * 50), 
                           y_limits = c(100, 300), 
                           legend_position = 'none') 

d <-plot_raw_boot_facet_layer  ("area",
                           y_breaks = c(1:6 * 10), 
                           y_limits = c(0, 40), 
                           legend_position = 'none') 

ggarrange(a,b,
          c,d,
          ncol = 2, nrow = 2)

ggsave("Fig2.svg", plot = last_plot(), path =here("output_plot"),
       width = 7.6, height = 7.5, units = "in")
```


```{r}
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Kmean_CovM_20230104.RData.RData"))
```


# generate figure
```{r}


a <-plot_raw_boot_facet_layer  ("silhs_mean_before_stat",
                           y_breaks = c(1:6 * 0.2 ), 
                           y_limits = c(0, 1), 
                           legend_position = 'none') 

b <-plot_raw_boot_facet_layer  ("n_cls",
                           y_breaks = c(1:6 * 3), 
                           y_limits = c(0, 15), 
                           legend_position = 'none') 

c <-plot_raw_boot_facet_layer  ("r_allpair_mean",
                           y_breaks = c(1:6 * 0.4), 
                           y_limits = c(-1, 1), 
                           legend_position = 'none') 

d <-plot_raw_boot_facet_layer  ("cluster_r_all_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0,1.2), 
                           legend_position = 'none') 

e <-plot_raw_boot_facet_layer  ("cluster_r_zf_all_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = 'none') 




ggarrange(a,b,
          c,d,
          e,
          ncol = 2, nrow = 3)

ggsave("Keman_All1.svg", plot = last_plot(), path =here("output_plot"),
       width = 7.6, height = 10, units = "in")
```

```{r}
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Basic_Parameter_MeanVersion_withCorr_20230113.RData.RData"))
```

# generate figure-supp
```{r}

a <-plot_raw_boot_facet_layer  ("amp",
                           y_breaks = c(1:6 *5), 
                           y_limits = c(0,15), 
                           legend_position = 'none')

b <-plot_raw_boot_facet_layer  ("area",
                           y_breaks = c(1:6 *10), 
                           y_limits = c(0,40), 
                           legend_position = 'none') 

c <-plot_raw_boot_facet_layer  ("synchrony_peak",
                           y_breaks = c(1:6 * 0.1), 
                           y_limits = c(0, 0.4), 
                           legend_position = 'none') 

```


```{r}
ggarrange(a,b,c,
          ncol = 3, nrow = 1)
ggsave("SuppFig8_part1.svg", plot = last_plot(), path =here("output_plot"),
       width = 10.6, height = 2.2, units = "in")
```



```{r}
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Kmean_CovM_20230104.RData.RData"))
```


```{r}

d <-  plot_raw_boot_facet_layer ("r_zf_allpair_mean",
                           y_breaks = c(1:6 * 0.2 ), 
                           y_limits = c(0, 1), 
                           legend_position = 'none') 

e <-  plot_raw_boot_facet_layer ("n_cls",
                           y_breaks = c(1:6 *3 ), 
                           y_limits = c(0, 15), 
                           legend_position = 'none') 

f<-  plot_raw_boot_facet_layer ("cluster_r_zf_all_mean",
                           y_breaks = c(1:6 * 0.2 ), 
                           y_limits = c(0, 1), 
                           legend_position = 'none') 


```


```{r}
ggarrange(d,e,f,
          ncol = 3, nrow = 1)
ggsave("SuppFig8_part2.svg", plot = last_plot(), path =here("output_plot"),
       width = 10.6, height = 2.2, units = "in")
```


# generate figure-supp
```{r}

a <-plot_raw_boot_facet_layer  ("cells_not_in_assembly",
                           y_breaks = c(1:6 * 20), 
                           y_limits = c(0, 100), 
                           legend_position = 'none') 

b <-plot_raw_boot_facet_layer  ("cells_in_one_assembly",
                           y_breaks = c(1:6 *20), 
                           y_limits = c(0,100), 
                           legend_position = 'none') 

c <-plot_raw_boot_facet_layer  ("cells_in_many_assembly",
                           y_breaks = c(1:6 * 20), 
                           y_limits = c(0, 100), 
                           legend_position = 'none') 

ggarrange(a,b,c,
          ncol = 3, nrow = 1)

ggsave("Keman_config.svg", plot = last_plot(), path =here("output_plot"),
       width = 10.3, height = 2.2, units = "in")
```


# generate figure-supp
```{r}

d <-plot_raw_boot_facet_layer  ("pw_neuron_neuron",
                           y_breaks = c(1:6 * 50), 
                           y_limits = c(0, 300), 
                           legend_position = 'none') 

e <-plot_raw_boot_facet_layer  ("neuron_centroid",
                           y_breaks = c(1:6 *50), 
                           y_limits = c(0,200), 
                           legend_position = 'none') 

f <-plot_raw_boot_facet_layer  ("centroid_centroid",
                           y_breaks = c(1:6 * 100), 
                           y_limits = c(0, 400), 
                           legend_position = 'none') 

ggarrange(d,e,f,
          ncol = 3, nrow = 1)

ggsave("Keman_Distance.svg", plot = last_plot(), path =here("output_plot"),
       width = 10.3, height = 2.2, units = "in")
```
