---
title: "Figure 5"
output:
  html_document: default
  word_document: default
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(warning = FALSE,echo = FALSE, message = FALSE,comment = NA)

freshr::freshr()
library(here)
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
library(pbkrtest)
library(lme4)
library(lmeresampler)
library(ggpubr)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set(theme_bw())
theme_set (theme_classic(base_size = 10, base_family = "sans"))
#dependent function
library(here)
source (here("src", "Develop_FGFRcKO_Function_posthoc_20230727.R"))
```


#### Figure 5A (Single-cluster (%))
```{r}
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Kmean_CovM_20230104.RData.RData"))
```

```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_layer  ("cells_in_one_assembly",
                           title = "",
                           y_breaks = c(1:6 * 20), 
                           y_limits = c(0, 100), 
                           legend_position = "right") 
```

```{r}
report_main_effect("cells_in_one_assembly")
report_inter_age_group_layer("cells_in_one_assembly")
```


#### Figure 5B (Non-cluster (%))
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_layer  ("cells_not_in_assembly",
                           title = "",
                           y_breaks = c(1:6 * 20), 
                           y_limits = c(0, 100), 
                           legend_position = "right") 
```

```{r}
report_main_effect("cells_not_in_assembly")
report_inter_age_group_layer("cells_not_in_assembly")
```


#### Figure 5C (Multiple-cluster (%))
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_layer  ("cells_in_many_assembly",
                           y_breaks = c(1:6 * 20), 
                           y_limits = c(0, 100), 
                           legend_position = "right",
                           title = "") 
```

```{r}
report_main_effect("cells_in_many_assembly")
report_inter_age_group_layer("cells_in_many_assembly")
```

#### Figure 5D (Pairwise distances between neurons)
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_layer  ("pw_neuron_neuron",
                           y_breaks = c(1:6 *50), 
                           y_limits = c(0, 300), 
                           legend_position = "right",
                           title = "") 
```

```{r}
report_main_effect("pw_neuron_neuron")
report_inter_age_group_layer("pw_neuron_neuron")
```


#### Figure 5E (Distance of neuron to subnetwork centroid)
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_layer  ("neuron_centroid",
                           y_breaks = c(1:6 *50), 
                           y_limits = c(0, 200), 
                           legend_position = "right",
                           title = "") 
```

```{r}
report_main_effect("neuron_centroid")
report_inter_age_group_layer("neuron_centroid")
```


#### Figure 5D (Pairwise distances subnetwork centroids)
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_layer  ("centroid_centroid",
                           y_breaks = c(1:6 *100), 
                           y_limits = c(0, 400), 
                           legend_position = "right",
                           title = "") 
```

```{r}
report_main_effect("centroid_centroid")
report_inter_age_group_layer("centroid_centroid")
```

