---
title: "Figure supp5A-E"
output:
  html_document: default
  word_document: default
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(warning = FALSE,echo = FALSE, message = FALSE,comment = NA)

freshr::freshr()
library(here)
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
library(pbkrtest)
library(lme4)
library(lmeresampler)
library(ggpubr)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set(theme_bw())
theme_set (theme_classic(base_size = 10, base_family = "sans"))
#dependent function
library(here)
source (here("src", "Develop_FGFRcKO_Function_posthoc_20230727.R"))
```


#### Figure supp5A (Pearson correlation coefficient-all pairs)
```{r}
load (here("output","2023-07-27_SummaryAll_FGFR-tri-cKO_Kmean_CovM_20230104.RData.RData"))
```

```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_layer  ("r_zf_allpair_mean",
                           title = "",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = "right") 
```

```{r}
report_main_effect("r_zf_allpair_mean")
report_inter_age_group_layer("r_zf_allpair_mean")
```



#### Figure supp5B (Subnetwork number))
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_layer  ("n_cls",
                           title = "",
                           y_breaks = c(1:6 * 3), 
                           y_limits = c(0, 15), 
                           legend_position = "n_cls") 
```

```{r}
report_main_effect("n_cls")
report_inter_age_group_layer("n_cls")
```



#### Figure supp5C (view in-out)
```{r}
load (here("output","2023-12-04_SummaryAll_FGFR-tri-cKO_Tetrac_Pearson_in_out_clusterV2_20231204.RData"))
```

```{r,fig.width = 6, fig.asp =1, echo=FALSE}
layer.label = c("Layer 2/3", "Layer 4")
names(layer.label) = c("2", "4")
sex.label = c("Female", "Male")
names(sex.label) = c("F", "M")
age.label = c("P11", "P13","P15", "P18", "P21")
names(age.label) = c("11", "13", "15", "18", "21")

df_lite_fig = df_lite %>%
        select(subject_id,location,group,f.age,f.layer,in_r_mean, out_r_mean)%>%
        drop_na(out_r_mean) %>%
        tidyr::unite(col = "set", c("subject_id","location","f.layer","group","in_r_mean"), remove = FALSE)%>%
        gather (condition,r_value, in_r_mean : out_r_mean,factor_key=TRUE)
        
ggplot(df_lite_fig,
    aes(x = factor(condition, levels = c("in_r_mean","out_r_mean")),
           y = r_value)) +
    geom_line(data = df_lite_fig, 
              aes(group = set, color = group), alpha = 0.5, linewidth = 0.5) +
    scale_x_discrete(labels = c("in", "out")) +
    facet_grid(f.layer ~f.age,labeller = labeller(f.age = age.label, f.layer = layer.label) )+ 
    labs(x = "", y = "") +
    scale_y_continuous(breaks = c(-1, -0.5, 0,0.5,1), limits = c(-1,1))+
    theme(legend.position = "right",
          legend.justification = "top",
          legend.title = element_blank(),
          legend.text = element_text(color = "black", size  = "10"),
          panel.spacing = unit(0, "lines"),
          strip.background = element_blank(),
          #strip.background = element_rect(color = "black", linewidth = 1),
          #strip.placement = ("outside"),
          #strip.text = element_text(size = 10),
          axis.text.x = element_text(color = "black", size = "10"),
          axis.line.x.bottom = element_line (linewidth = 1/2),
          axis.text.y = element_text(color = "black", size = "10"),
          axis.line.y = element_line(linewidth = 1/2), 
          axis.ticks.x = element_blank(),
          plot.background = element_blank(),
          plot.margin = unit(c(0,0.5,1,0), 'cm'))+
    ggsci::scale_color_d3()+
    annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf)
```



#### Figure supp5D (tCC- in the same subnetwork)
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_layer  ("in_r_mean",
                           y_breaks = c(1:6 * 0.2), 
                           y_limits = c(0, 1), 
                           legend_position = "right",
                           title = "") 
```

```{r}
report_main_effect("in_r_mean")
report_inter_age_group_layer("in_r_mean")
```



#### Figure supp5E (tCC- outside the subnetwork)
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
plot_raw_boot_facet_layer  ("out_r_mean",
                           y_breaks = seq(-1, 1 , by=0.5), 
                           y_limits = c(-1, 1), 
                           legend_position = "right",
                           title = "") 
```

```{r}
report_main_effect("out_r_mean")
report_inter_age_group_layer("out_r_mean")
```


