---
title: "WT_Dlx_GsDREADD_Kmean_CovM_in_out Cluster"
output: html_document
date: "2023-12-06"
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

freshr::freshr()
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(tidyr)
library(extrafont)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set (theme_classic(base_size = 10, base_family = "sans"))

##libraries for color
library(ggsci)
library(wesanderson)
#names(wes_palettes)
library(colorBlindness)
library(viridis)

library(here)
# only work this way, when code is located in analysis folder
source (here("src", "WT_Dlx_GsDREADD_Function_posthoc_20230217.R"))

load (here("output","2023-12-06_Caseboot_SummaryWT_Dlx_GsDREADD_kmean_CovM_Corr_in_outV2_20231204.RData"))
```



# r_allpair_mean
```{r,fig.width = 3, fig.asp = 1, echo=FALSE}
plot_raw ("r_allpair_mean",
         y_breaks = c(1:6 * 0.2), 
         y_limits = c(-0.4, 1), 
         legend_position = "none")
```

```{r}
report_main("r_allpair_mean")
report_all_interaction_simple("r_allpair_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_all_interaction("r_allpair_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_interaction("r_allpair_mean", var_int1 = "p15_cno", var_int2 = "sex")
report_interaction("r_allpair_mean", var_int1 = "p15_cno", var_int2 = "f.layer")
```


# in_r_mean
```{r,fig.width = 3, fig.asp = 1,echo=FALSE}

plot_raw ("in_r_mean",
         y_breaks = c(1:6 * 0.2), 
         y_limits = c(0, 1), 
         legend_position = "none")
```

```{r}
report_main("in_r_mean")
report_all_interaction_simple("in_r_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_all_interaction("in_r_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_interaction("in_r_mean", var_int1 = "p15_cno", var_int2 = "sex")
report_interaction("in_r_mean", var_int1 = "p15_cno", var_int2 = "f.layer")
```

# out_r_mean
```{r, fig.width = 3, fig.asp = 1, ,echo=FALSE}

plot_raw("out_r_mean",
         y_breaks = c(1:6 * 0.2), 
         y_limits = c(-0.2, 1), 
         #legend_position = "right"
         legend_position = "none")
#ggsave("out_r_mean.svg", plot = last_plot(), path =here("output_plot"),
#       width = 2, height = 2.2, units = "in")
```

```{r}
report_main("out_r_mean")
report_all_interaction_simple("out_r_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_all_interaction("out_r_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_interaction("out_r_mean", var_int1 = "p15_cno", var_int2 = "sex")
report_interaction("out_r_mean", var_int1 = "p15_cno", var_int2 = "f.layer")
```

# r_diff
```{r, fig.width = 3, fig.asp = 1}

plot_raw("r_diff",
         y_breaks = c(1:6 * 0.2), 
         y_limits = c(0, 1), 
         #legend_position = "right"
         legend_position = "none")

```

```{r}
report_main("r_diff")
report_all_interaction_simple("r_diff", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_all_interaction("r_diff", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_interaction("r_diff", var_int1 = "p15_cno", var_int2 = "sex")
report_interaction("r_diff", var_int1 = "p15_cno", var_int2 = "f.layer")
```




# zf_r_allpair_mean
```{r, fig.width = 3, fig.asp = 1, echo=FALSE}

plot_raw("zf_r_allpair_mean",
         y_breaks = c(1:6 * 0.2), 
         y_limits = c(0, 1), 
         legend_position = "none")
#ggsave("zf_r_allpair_mean.svg", plot = last_plot(), path =here("output_plot"),
#       width = 2, height = 2.2, units = "in")


```

```{r}
report_main("zf_r_allpair_mean")
report_all_interaction_simple("zf_r_allpair_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_all_interaction("zf_r_allpair_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_interaction("zf_r_allpair_mean", var_int1 = "p15_cno", var_int2 = "sex")
report_interaction("zf_r_allpair_mean", var_int1 = "p15_cno", var_int2 = "f.layer")
```


# zf_in_r_mean
```{r, fig.width = 3, fig.asp = 1, echo=FALSE}
plot_raw ("zf_in_r_mean",
         y_breaks = c(1:6 * 0.2), 
         y_limits = c(0, 1), 
         legend_position = "none")


```

```{r}
report_main("zf_in_r_mean")
report_all_interaction_simple("zf_in_r_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_all_interaction("zf_in_r_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_interaction("zf_in_r_mean", var_int1 = "p15_cno", var_int2 = "sex")
report_interaction("zf_in_r_mean", var_int1 = "p15_cno", var_int2 = "f.layer")
```


# zf_out_r_mean
```{r, fig.width = 3, fig.asp = 1, echo = FALSE}
plot_raw ("zf_out_r_mean",
         y_breaks = c(1:6 * 0.2), 
         y_limits = c(0, 1), 
         legend_position = "none")
```

```{r}
report_main("zf_out_r_mean")
report_all_interaction_simple("zf_out_r_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_all_interaction("zf_out_r_mean", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_interaction("zf_out_r_mean", var_int1 = "p15_cno", var_int2 = "sex")
report_interaction("zf_out_r_mean", var_int1 = "p15_cno", var_int2 = "f.layer")
```


# zf_r_diff
```{r, fig.width = 3, fig.asp = 1, echo=FALSE}
plot_raw ("zf_r_diff",
         y_breaks = c(1:6 * 0.2), 
         y_limits = c(0, 0.6), 
         legend_position = "none")
```

```{r}
report_main("zf_r_diff")
report_all_interaction_simple("zf_r_diff", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_all_interaction("zf_r_diff", var_int1 = "p15_cno", var_int2 = "sex", var_int3 = "f.layer")
report_interaction("zf_r_diff", var_int1 = "p15_cno", var_int2 = "sex")
report_interaction("zf_r_diff", var_int1 = "p15_cno", var_int2 = "f.layer")
```

