---
title: "VGAT and Syt2 staining_somatic_input"
output:
  html_document: default
  pdf_document: default
date: "2023-08-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

freshr::freshr()
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(tidyr)
library(extrafont)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set (theme_classic(base_size = 10, base_family = "sans"))
library(ggpubr)
##libraries for color
library(ggsci)
#library(wesanderson)
#names(wes_palettes)
#library(colorBlindness)
#library(viridis)
```

```{r}
library(here)
# only work this way, when code is located in analysis folder
source (here("src", "VGAT_Syt2_Function_posthoc_20230804.R"))
load(here("output", "2023-08-04_P15_VGAT_SYT2_20230318_somatic_input.RData"))
```


```{r,fig.width = 8, fig.asp = 0.5, echo =FALSE}
#Plot figure
a <- plot_raw_boot_facet_layer("soma_volum_mm3",
         y_breaks = c(1:6 * 500), 
         y_limits = c(0, 2500),
         title = "",
         legend_position = "none")

b <- plot_raw_boot_facet_layer("vgat_punctate_number_on_soma_normalized",
         y_breaks = c(1:6 * 5), 
         y_limits = c(0, 20),
         title = "",
         legend_position = "none")

c <- plot_raw_boot_facet_layer("syt2_punctate_number_on_soma_normalized",
         y_breaks = c(1:6 * 5), 
         y_limits = c(0, 20),
         title = "",
         legend_position = "none")

d <- plot_raw_boot_facet_layer("vgat_and_syt2_punctate_number_on_soma_normalized",
         y_breaks = c(1:6 * 5), 
         y_limits = c(0, 20),
         title = "",
         legend_position = "none")


ggarrange(a, b, 
          c, d,
          ncol = 4, nrow = 1)

ggsave("Density.svg", plot = last_plot(), path =here("output_plot"),
       width = 8.1, height = 2.5, units = "in")
```



```{r,fig.width = 8, fig.asp = 0.8, echo =FALSE}
#Plot figure
a <- plot_raw_boot_facet_layer("soma_volum_mm3",
         y_breaks = c(1:6 * 500), 
         y_limits = c(0, 2500),
         legend_position = "none")

b <- plot_raw_boot_facet_layer("vgat_punctate_number_on_soma",
         y_breaks = c(1:6 * 50), 
         y_limits = c(0, 300),
         legend_position = "none")


c <- plot_raw_boot_facet_layer("syt2_punctate_number_on_soma",
         y_breaks = c(1:6 * 40), 
         y_limits = c(0, 200),
         legend_position = "none")

d <- plot_raw_boot_facet_layer("vgat_and_syt2_punctate_number_on_soma",
         y_breaks = c(1:6 * 40), 
         y_limits = c(0, 200),
         legend_position = "none")
e<- plot_raw_boot_facet_layer("syt2_neg_vgat_punctate_number_on_soma",
         y_breaks = c(1:6 * 40), 
         y_limits = c(0, 200),
         legend_position = "none")

ggarrange(a, b, 
          c, d,
          e,
          ncol = 2, nrow = 3)

#ggsave("Density.svg", plot = last_plot(), path =here("output_plot"),
#       width = 3, height = 2, units = "in")
```


```{r,fig.width = 8, fig.asp = 0.7, echo=FALSE}
#Plot figure
a <- plot_raw_boot_facet_layer("vgat_punctate_number_on_soma_normalized",
         y_breaks = c(1:6 * 5), 
         y_limits = c(0, 20),
         legend_position = "none")

b <- plot_raw_boot_facet_layer("syt2_punctate_number_on_soma_normalized",
         y_breaks = c(1:6 * 5), 
         y_limits = c(0, 20),
         legend_position = "none")

c <- plot_raw_boot_facet_layer("vgat_and_syt2_punctate_number_on_soma_normalized",
         y_breaks = c(1:6 * 5), 
         y_limits = c(0, 20),
         legend_position = "none")


d <- plot_raw_boot_facet_layer("syt2_neg_vgat_punctate_number_on_soma_normalized",
         y_breaks = c(1:6 * 5), 
         y_limits = c(0, 20),
         legend_position = "none")

ggarrange(a, b,
          c, d,
          ncol = 2, nrow = 2)

#ggsave("Density.svg", plot = last_plot(), path =here("output_plot"),
#       width = 3, height = 2, units = "in")
```


# soma_volum_mm3
```{r}
report_main_effect("soma_volum_mm3")
report_interaction("soma_volum_mm3", var_int1 = "layer", var_int2 = "sex")
```


# vgat_punctate_number_on_soma
```{r,fig.width = 5, fig.asp = 0.5}
report_main_effect("vgat_punctate_number_on_soma")
report_interaction("vgat_punctate_number_on_soma", var_int1 = "layer", var_int2 = "sex")
```

# syt2_punctate_number_on_soma
```{r,fig.width = 5, fig.asp = 0.5}
report_main_effect("syt2_punctate_number_on_soma")
report_interaction("syt2_punctate_number_on_soma", var_int1 = "layer", var_int2 = "sex")
```
# vgat_and_syt2_punctate_number_on_soma
```{r,fig.width = 5, fig.asp = 0.5}
report_main_effect("vgat_and_syt2_punctate_number_on_soma")
report_interaction("vgat_and_syt2_punctate_number_on_soma", var_int1 = "layer", var_int2 = "sex")
```


# syt2_neg_vgat_punctate_number_on_soma
```{r,fig.width = 5, fig.asp = 0.5}
report_main_effect("syt2_neg_vgat_punctate_number_on_soma")
report_interaction("syt2_neg_vgat_punctate_number_on_soma", var_int1 = "layer", var_int2 = "sex")
```

# vgat_punctate_number_on_soma_normalized
```{r,fig.width = 5, fig.asp = 0.5}
report_main_effect("vgat_punctate_number_on_soma_normalized")
report_interaction("vgat_punctate_number_on_soma_normalized", var_int1 = "layer", var_int2 = "sex")
```

# syt2_punctate_number_on_soma_normalized
```{r,fig.width = 5, fig.asp = 0.5}
report_main_effect("syt2_punctate_number_on_soma_normalized")
report_interaction("syt2_punctate_number_on_soma_normalized", var_int1 = "layer", var_int2 = "sex")
```

# vgat_and_syt2_punctate_number_on_soma_normalized
```{r,fig.width = 5, fig.asp = 0.5}
report_main_effect("vgat_and_syt2_punctate_number_on_soma_normalized")
report_interaction("vgat_and_syt2_punctate_number_on_soma_normalized", var_int1 = "layer", var_int2 = "sex")
```

# vsyt2_neg_vgat_punctate_number_on_soma_normalized
```{r,fig.width = 5, fig.asp = 0.5}
report_main_effect("syt2_neg_vgat_punctate_number_on_soma_normalized")
report_interaction("syt2_neg_vgat_punctate_number_on_soma_normalized", var_int1 = "layer", var_int2 = "sex")
```