---
title: "Figure Supp9 - VGAT and Syt2 staining"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, comment = "")

freshr::freshr()
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(tidyr)
library(extrafont)
library(ggpubr)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set (theme_classic(base_size = 10, base_family = "sans"))

##libraries for color
library(ggsci)
#library(wesanderson)
#names(wes_palettes)
#library(colorBlindness)
#library(viridis)
library(here)
# only work this way, when code is located in analysis folder
source (here("src", "VGAT_Syt2_Function_posthoc_20230804.R"))
```


```{r}
#result source
load(here("output", "2023-03-21_P15_VGAT_SYT2_20230318.RData"))
```


#### Figure 7C (VGAT in neuropil)
```{r,echo=FALSE}
plot_raw_boot_facet_layer("density_number_100_um_3_vgat_number",
         y_breaks = seq(0,100, by= 5), 
         y_limits = c(0, 25),
         legend_position = "right",
         title = "VGAT in neuropil")
```

```{r,fig.width = 5, fig.asp = 0.5}
report_main_effect("density_number_100_um_3_vgat_number")
report_interaction("density_number_100_um_3_vgat_number", var_int1 = "layer", var_int2 = "sex")
```


#### Figure 7D (Syt2 in neuropil)
```{r,echo=FALSE}
plot_raw_boot_facet_layer("density_number_100_um_3_syt2_number",
         y_breaks = seq(0,100, by= 5), 
         y_limits = c(0, 20),
         legend_position = "right",
         title = "Syt2 in neuropil")
```

```{r,fig.width = 2, fig.asp = 1}
report_main_effect("density_number_100_um_3_syt2_number")
report_interaction("density_number_100_um_3_syt2_number", var_int1 = "layer", var_int2 = "sex")
```


#### Figure 7E (VGAT and Syt2 colocalized in neuropil)
```{r,echo=FALSE}
plot_raw_boot_facet_layer("density_of_colocalized_signal_number_100_um_3_vgat_and_syt2_punctate_number",
         y_breaks =seq(0,100, by= 5), 
         y_limits = c(0, 20),
         legend_position = "right",
         title = "VGAT and Syt2 colocalized in neuropil")
```

```{r,fig.width = 2, fig.asp = 1}
report_main_effect("density_of_colocalized_signal_number_100_um_3_vgat_and_syt2_punctate_number")
report_interaction("density_of_colocalized_signal_number_100_um_3_vgat_and_syt2_punctate_number", var_int1 = "layer", var_int2 = "sex")
```


#### Figure 7F (Soma volumn)
```{r,echo=FALSE}
#result source
load(here("output", "2023-08-04_P15_VGAT_SYT2_20230318_somatic_input.RData"))
```

```{r}
plot_raw_boot_facet_layer("soma_volum_mm3",
         y_breaks = seq(0,3000, by = 500), 
         y_limits = c(0, 2500),
         title = "Soma volumn",
         legend_position = "right")
```

```{r}
report_main_effect("soma_volum_mm3")
report_interaction("soma_volum_mm3", var_int1 = "layer", var_int2 = "sex")
```


#### Figure 7G (VGAT and Syt2 colocalized on soma)
```{r,echo=FALSE}
plot_raw_boot_facet_layer("vgat_and_syt2_punctate_number_on_soma_normalized",
         y_breaks = seq(0, 100, by=4), 
         y_limits = c(0, 12),
         title = "VGAT and Syt2 colocalized on soma",
         legend_position = "right")
```

```{r,fig.width = 5, fig.asp = 0.5}
report_main_effect("vgat_and_syt2_punctate_number_on_soma_normalized")
report_interaction("vgat_and_syt2_punctate_number_on_soma_normalized", var_int1 = "layer", var_int2 = "sex")
```

