---
title: "Figure supp5G-J"
output:
  html_document: default
  word_document: default
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(warning = FALSE,echo = FALSE, message = FALSE,comment = NA)

freshr::freshr()
library(here)
library(dplyr)
library(car)
library(sjPlot)
library(gridExtra)
library(knitr)
library(tidyverse)
library(ggbeeswarm)
library(ggthemes)
library(emmeans)
library(parameters)
library(bayestestR)
library(ggplot2)
library(ggsci)
library(tinytex)
library(extrafont)
library(pbkrtest)
library(lme4)
library(lmeresampler)
library(ggpubr)
#list the Fonts in windows
#windowsFonts()
#set-theme for figure
theme_set(theme_bw())
theme_set (theme_classic(base_size = 10, base_family = "sans"))
#dependent function
library(here)
source (here("src", "Develop_FGFRcKO_Ephys_Function_posthoc_20230731.R"))
```


#### Figure supp5G (sEPSC Frequency)
```{r}
load (here("output","2023-07-31_FGFR-tri-Ncre_sEPSC_sIPSC_all_age_20230731.RData"))
```

```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
merge_sex_plot_raw_color_sex("s_epsc_freq",
                           title = "",
                           y_breaks = c(1:6 * 3), 
                           y_limits = c(0, 12), 
                           legend_position = "right") 
```

```{r}
report_main_effect("s_epsc_freq")
report_inter_age_group_sex("s_epsc_freq")
merge_sex_report_age_int_group("s_epsc_freq")

```



#### Figure supp5H (sEPSC amplitude)
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
merge_sex_plot_raw_color_sex("s_epsc_amp",
                           title = "",
                           y_breaks = c(1:6 * 5), 
                           y_limits = c(0, 30), 
                           legend_position = "right") 
```

```{r}
report_main_effect("s_epsc_amp")
report_inter_age_group_sex("s_epsc_amp")
merge_sex_report_age_int_group("s_epsc_amp")
```



#### Figure supp5I (sIPSC frequency)
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
merge_sex_plot_raw_color_sex("s_ipsc_freq",
                           title = "",
                           y_breaks = c(1:6 * 3), 
                           y_limits = c(0, 9), 
                           legend_position = "right") 
```

```{r}
report_main_effect("s_ipsc_freq")
report_inter_age_group_sex("s_ipsc_freq")
merge_sex_report_age_int_group("s_ipsc_freq")
```



#### Figure supp5J (sIPSC amplitude)
```{r, fig.width = 5, fig.asp = 0.5, echo=FALSE}
merge_sex_plot_raw_color_sex("s_ipsc_amp",
                           title = "",
                           y_breaks = c(1:6 * 10), 
                           y_limits = c(0, 50), 
                           legend_position = "right") 
```

```{r}
report_main_effect("s_ipsc_amp")
report_inter_age_group_sex("s_ipsc_amp")
merge_sex_report_age_int_group("s_ipsc_amp")
```
